/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import model.Appointments;
import model.Specialist;
import model.Users;
import service.AppointmentService;
import service.SpecialistService;

/**
 *
 * @author admin
 */
public class UpdateAppointment extends javax.swing.JFrame {

    /**
     * Creates new form UpdateAppointment
     */
    Appointments appointment = new Appointments();
    public UpdateAppointment() {
        initComponents();
    }
    public UpdateAppointment(Appointments appointments) {
        initComponents();
        loadDoctorsCombo();
        appointment = appointments;
        setFieldAppointmentAndPatientId(appointment);
    }
    private void loadDoctorsCombo(){
        try{
            Registry registry = LocateRegistry.getRegistry("127.0.0.1",5000);
            SpecialistService service = (SpecialistService)registry.lookup("specialist");
            List<Specialist> specialists = service.allSpecialists();
            if(specialists != null){
                for(Specialist sp: specialists){
                    DoctorCombo.addItem(sp.getDoctor_id()+"-"+sp.getDoctor_name());
                }
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    private void setFieldAppointmentAndPatientId(Appointments appointment){
        try{
            Registry registry =  LocateRegistry.getRegistry("127.0.0.1", 5000);
           AppointmentService intrf = (AppointmentService)registry.lookup("appointment");
           Appointments FoundAppointment = new Appointments();
           FoundAppointment  = intrf.getAppointmentById(appointment);
            //idTxt.setText(appointment.getAppId());
            int appId = FoundAppointment.getAppId();
            appointmentIDtxt.setText(appId + "");
            idTxt.setText(FoundAppointment.getPatient_id().getId()+ "");
            AppointTimeTxt.setText(FoundAppointment.getAppointment_time());
            genderTxt.setText(FoundAppointment.getGender());
            DoctorCombo.insertItemAt(String.valueOf(FoundAppointment.getDoctor_id().getDoctor_id()), 0);
            DoBCalendar.setDate(FoundAppointment.getDate_of_birth());
//            String appointmentDateStr = appointment.getAppointment_date();
//            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); // Specify the date format according to your needs
//            Date appointmentDate = dateFormat.parse(appointmentDateStr);
//            AppointDateCalendar.setDate(appointmentDate);

        }catch(Exception ex){
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        genderTxt = new javax.swing.JTextField();
        AppointTimeTxt = new javax.swing.JTextField();
        saveAppointmentBtn = new javax.swing.JButton();
        DoctorCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Doctor = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        appointmentIDtxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        DoBCalendar = new com.toedter.calendar.JDateChooser();
        AppointDateCalendar = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(8, 109, 229));
        jPanel4.setForeground(new java.awt.Color(0, 51, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/tooth-drill.png"))); // NOI18N
        jLabel9.setText("DentalConnect");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/newTeeth.JPG"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 130, 390, 390));

        jPanel3.setBackground(new java.awt.Color(60, 203, 234));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(8, 109, 229));
        jLabel1.setText("DENTAL APPOINTMENT");

        idTxt.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        idTxt.setEnabled(false);
        idTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTxtActionPerformed(evt);
            }
        });

        genderTxt.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        genderTxt.setText("Gender (M/F)");
        genderTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderTxtActionPerformed(evt);
            }
        });

        AppointTimeTxt.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        AppointTimeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppointTimeTxtActionPerformed(evt);
            }
        });

        saveAppointmentBtn.setBackground(new java.awt.Color(8, 109, 229));
        saveAppointmentBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveAppointmentBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveAppointmentBtn.setText("Update");
        saveAppointmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAppointmentBtnActionPerformed(evt);
            }
        });

        DoctorCombo.setMinimumSize(new java.awt.Dimension(56, 22));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Date Of Birth (DD/MM/YYYY)");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Appointment time (pm/am)");

        Doctor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Doctor.setText("Doctors");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Gender");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Appointment date");

        appointmentIDtxt.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        appointmentIDtxt.setEnabled(false);
        appointmentIDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointmentIDtxtActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Appointment ID");

        cancelBtn.setBackground(new java.awt.Color(204, 0, 0));
        cancelBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(Doctor)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idTxt)
                            .addComponent(AppointTimeTxt)
                            .addComponent(DoctorCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(genderTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(appointmentIDtxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DoBCalendar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(AppointDateCalendar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(cancelBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(saveAppointmentBtn)
                .addGap(213, 213, 213))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appointmentIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DoBCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addComponent(DoctorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AppointTimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Doctor)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel3)
                                .addGap(94, 94, 94)))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AppointDateCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveAppointmentBtn)
                    .addComponent(cancelBtn))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTxtActionPerformed

    private void genderTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderTxtActionPerformed

    private void AppointTimeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppointTimeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AppointTimeTxtActionPerformed

    private void saveAppointmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAppointmentBtnActionPerformed

    
   
        
     //String appointmentDate = dateFormat.format(AppointDateCalendar.getDate());
     
     //String dob = dateFormat.format(DoBCalendar.getDate());
    
    
   
    String selectedDoctor = DoctorCombo.getSelectedItem().toString();

    // Determine which fields have been filled in
    

       Appointments appointment1= new Appointments();
       appointment1.setAppId(Integer.parseInt(appointmentIDtxt.getText()));
       Users patient = new Users();
       patient.setId(Integer.parseInt(idTxt.getText()));
       appointment1.setPatient_id(patient);
       appointment1.setDate_of_birth(DoBCalendar.getDate());
       appointment1.setGender(genderTxt.getText());
       int id = Integer.parseInt(selectedDoctor.substring(0, selectedDoctor.indexOf("-")));
       Specialist doctor = new Specialist();
       doctor.setDoctor_id(id);
       appointment1.setDoctor_id(doctor);
       appointment1.setAppointment_time(AppointTimeTxt.getText());
       String appointmentDate =AppointDateCalendar.getDate().toString();
       appointment1.setAppointment_date(appointmentDate);
  

   

    try{
            
            appointment1.setPatient_id(appointment.getPatient_id());

            Registry reg = LocateRegistry.getRegistry("127.0.0.1", 5000);
            AppointmentService as = (AppointmentService)reg.lookup("appointment");
            String feedback = as.updateAppointment(appointment1);
            JOptionPane.showMessageDialog(this, feedback, "Successful", JOptionPane.INFORMATION_MESSAGE);
            Users loggedUser = new Users();
            loggedUser.setId(Integer.parseInt(idTxt.getText()));
            UserDashboard page = new UserDashboard(loggedUser);
            dispose();
            page.setVisible(true);

        
    } catch (Exception ex) {
        ex.printStackTrace();
    }
    }//GEN-LAST:event_saveAppointmentBtnActionPerformed

    private void appointmentIDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmentIDtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appointmentIDtxtActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this, "Appointment update cancelled");
         Users loggedUser= new Users();
         loggedUser.setId(Integer.parseInt(idTxt.getText()));
         UserDashboard page = new UserDashboard(loggedUser);
         dispose();
         page.setVisible(true);
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateAppointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser AppointDateCalendar;
    private javax.swing.JTextField AppointTimeTxt;
    private com.toedter.calendar.JDateChooser DoBCalendar;
    private javax.swing.JLabel Doctor;
    private javax.swing.JComboBox<String> DoctorCombo;
    private javax.swing.JTextField appointmentIDtxt;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField genderTxt;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton saveAppointmentBtn;
    // End of variables declaration//GEN-END:variables
}
